baseURL = "https://williamswang.win"
languageCode = "en-us"
title = "Williams Wang Site"
theme = "ananke"

relativeURLs = true
canonifyURLs = true

[params]
  author = "Williams Wang"
  description = "Williams Wang Blog"

